# -*- coding: utf-8 -*-
"""EX-EBAC-M4-AD

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E5SCsPAYesHcv0lmjVghUT17-DoKl1vJ
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile musica.txt
# Roda Viva
# Chico Buarque
# 
# Tem dias que a gente se sente
# Como quem partiu ou morreu
# A gente estancou de repente
# Ou foi o mundo então que cresceu
# A gente quer ter voz ativa
# No nosso destino mandar
# Mas eis que chega a roda viva
# E carrega o destino pra lá
# 
# Roda mundo, roda-gigante
# Roda moinho, roda pião
# 
# O tempo rodou num instante
# Nas voltas do meu coração
# A gente vai contra a corrente
# Até não poder resistir
# Na volta do barco é que sente
# O quanto deixou de cumprir
# Faz tempo que a gente cultiva
# A mais linda roseira que há
# Mas eis que chega a roda viva
# E carrega a roseira pra lá
# 
# Roda mundo, roda-gigante
# Roda moinho, roda pião

# Commented out IPython magic to ensure Python compatibility.
# %%writefile carros.csv
# id,valor_venda,valor_manutencao,portas,pessoas,porta_malas
# 1,vhigh,med,2,2,small
# 2,med,vhigh,2,2,small
# 3,low,vhigh,2,2,small
# 4,low,high,2,2,small
# 5,low,high,2,2,small
# 6,low,high,4,4,big
# 7,low,high,4,4,big
# 8,low,med,2,2,small
# 9,low,med,2,2,small
# 10,low,med,2,2,small
# 11,low,med,4,4,big
# 12,low,low,2,2,small
# 13,low,low,4,4,small
# 14,low,low,4,4,med

"""## 1. Extração de coluna de arquivo csv

1.1. Extraia os valores `valor_venda` e armazena em uma lista.
"""

valor_venda = []

with open(file='./carros.csv', mode='r', encoding='utf8') as arquivo:
    next(arquivo)
    for linha in arquivo:
        colunas = linha.split(',')
        valor_venda.append(colunas[1].strip())

print(valor_venda)

def extrai_coluna_csv(nome_arquivo: str, indice_coluna: int):
    coluna = []

    with open(nome_arquivo, mode='r', encoding='utf8') as arquivo:
        for i, linha in enumerate(arquivo):
            if i == 0:
                continue  # Pula a primeira linha (cabeçalho)
            colunas = linha.split(',')
            if len(colunas) > indice_coluna:
                coluna.append(colunas[indice_coluna].strip())

    return coluna

# extrair a coluna valor_manutencao
valor_manutencao = extrai_coluna_csv(nome_arquivo='./carros.csv', indice_coluna=2)
print(valor_manutencao) # deve retornar ['med', 'vhigh', 'vhigh', ...

# extrair a coluna porta_malas
porta_malas = extrai_coluna_csv(nome_arquivo='./carros.csv', indice_coluna=5)
print(porta_malas) # deve retornar ['small', 'small', 'small', ...]

"""## 1\. Funções para arquivo csv

"""

def extrai_coluna_csv(nome_arquivo: str, indice_coluna: int, tipo_dado: str):
    coluna = []

    with open(nome_arquivo, mode='r', encoding='utf8') as arquivo:
        for i, linha in enumerate(arquivo):
            if i == 0:
                continue  # Pula a primeira linha (cabeçalho)
            colunas = linha.split(',')
            if len(colunas) > indice_coluna:
                valor = colunas[indice_coluna].strip()
                if tipo_dado == 'int':
                    coluna.append(int(valor))
                elif tipo_dado == 'float':
                    coluna.append(float(valor))
                else:
                    coluna.append(valor)

    return coluna

valor_venda = extrai_coluna_csv(nome_arquivo='./carros.csv', indice_coluna=1, tipo_dado='str')
print(valor_venda)

pessoas = extrai_coluna_csv(nome_arquivo='./carros.csv', indice_coluna=4, tipo_dado='int')
print(pessoas)

"""## 2\. Funções para arquivo txt

"""

def extrai_linha_txt(nome_arquivo: str, numero_linha: int):
    palavras_linha = []

    with open(nome_arquivo, mode='r', encoding='utf8') as arquivo:
        for i, linha in enumerate(arquivo):
            if i + 1 == numero_linha:  # i começa em 0, então adicionamos 1 para contar as linhas
                palavras_linha = linha.split()  # Quebra a linha em palavras usando espaços como separador
                break  # Para de ler o arquivo após encontrar a linha desejada

    return palavras_linha

linha10 = extrai_linha_txt(nome_arquivo='./musica.txt', numero_linha=10)
print(linha10)